modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="ashenremains"
version="1.0.0"
displayName="Ashen Remains"
displayURL="https://prcrichards.wixsite.com/portfolio"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Mindthemoods"
description="Burn everything!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.ashenremains]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration